### ISSUE TITLE
when using environment variable in the values.yaml file getting "java.io.IOException: Stream closed" exception when copy values.yaml file into build folder

### ISSUE THREAD

**Issue by cosemachi** [unbroken-dome/gradle-helm-plugin#117] opened 2021-02-16 15:43 UTC
Hi,

We are using some environment variable in the values.yaml file, for example define value like this:
logging: "$(LOG_ROOT)/$(COMPONENT)/$(HOSTNAME)" 

above "LOG_ROOT", "COMPONENT" and "HOSTNAME" are set as environment variables in the deployment.yaml file.

But when running snapshot build, or any helmPackage task in gralde, kept getting following exception:
"Execution failed for task ':{subproject}:helmFilterXXXChartSources'.

Could not copy file '/.../values.yaml' to '/.../build/.../values.yaml'.
java.io.IOException: Stream closed"

Looks like there are some extra filter was done that cannot handle string that having "$(" in the value file.

Thanks!

**Comment by vkarev** [comment] 2021-02-18 22:40
Same thing with regexp patterns in values.yaml, e.g.: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
Removing $ from pattern helps, but this won't work.

**Comment by hpschry** [comment] 2021-02-23 10:32
Experiencing the same, when values yaml contains regular expression.

**Comment by Woxis17** [comment] 2021-04-13 10:07
I encountered the same problem. For me the solution was to escape the dollar sign in values.yaml from
`host: $HOST` to `host: \$HOST`

**Comment by tkrullmann** [comment] 2021-11-10 11:00
Hi,

the suggestion of @Woxis17 is correct, when using dollar signs in the filtered files they need to be escaped as `\$` (or filtering needs to be disabled by setting `filtering.enabled.set(false)`).

The "stream closed" error was caused by my implementation of filtering "swallowing" other errors when reading the file -- this is fixed by the above PR.

With the fix, now I get a proper error message pointing at the problem:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':helmFilterExampleChartSources'.
> Could not copy file '/Users/till/git/unbroken-dome/helm-plugin-filtering-issue/src/main/example/values.yaml' to '/Users/till/git/unbroken-dome/helm-plugin-filtering-issue/build/tmp/helm/filtered/example/values.yaml'.
   > Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
     SimpleTemplateScript18.groovy: 1: token recognition error at: '(' @ line 1, column 26.
        out.print("""logging: \"$(LOG_ROOT)/$(COMPONENT)/$(HOSTNAME)\"
                                 ^
```

This still doesn't point out that the escaping needs to be done, but it's at least a bit clearer that there's something wrong with that expression. I also added a paragraph to the documentation about escaping the dollar-signs.

**Closed** 2021-11-10 11:00 UTC
