### ISSUE TITLE
linting not working for me

### ISSUE THREAD

**Issue by mhobotpplnet** [unbroken-dome/gradle-helm-plugin#9] opened 2019-06-04 04:06 UTC
Not sure what I am doing wrong but basically I just want to lint a chart. 

Getting this error for some odd reason

```
* What went wrong:
A problem was found with the configuration of task 'my-tool:helmLintMy-toolChart'.
> Directory '/Users/*****/.helm
  ' specified for property '$1' does not exist.
```
I just ran 
./gradlew helmLintMy-toolChart

Am trying to do step by step 
lint , package, deploy

**Comment by kozchris** [comment] 2019-06-09 19:14
I'm getting the same thing with the helmPackage task. When I run `gradle helmPackage --debug` i see the helm home command run and finish with exit code 0.

I can see the directory, seems to have the correct permissions, and it is empty.

`14:57:16.130 [INFO] [org.unbrokendome.gradle.plugins.helm.command.HelmExecProviderSupport] Executing: [helm, home]
14:57:16.130 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'helm''. Working directory: /Users/chris/Documents/git/images/mms-activemq Command: helm home
14:57:16.130 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'helm'': {PATH=/Users/chris/bin: <removed some paths for clarity>... SHLVL=1, HOME=/Users/chris, APP_NAME_44546=Gradle}
14:57:16.130 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
14:57:16.130 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'helm'.
14:57:16.135 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
14:57:16.135 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
14:57:16.135 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'helm''
14:57:16.193 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
14:57:16.193 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'helm'' finished with exit value 0 (state: SUCCEEDED)
`
After that I see the exception.
`14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem was found with the configuration of task ':mms-activemq:helmLintMainChart'.
14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Directory '/Users/chris/.helm
14:57:16.196 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ' specified for property '$1' does not exist.
`

Just starting out with helm charts and this plugin so I guess I am missing some required configuration. If there is something I can do to help debug this issue let me know.

**Comment by kozchris** [comment] 2019-06-09 19:19
adding 
`helm {
    home = file("$buildDir/helm/home")
}`

I see the error message adjust accordingly to show this path.

`* What went wrong:
A problem was found with the configuration of task ':mms-activemq:helmLintMainChart'.
> Directory '<my buildDir>/helm/home' specified for property '$1' does not exist.
`

**Comment by kozchris** [comment] 2019-06-09 19:27
As soon as I manually created `$buildDir/helm/home` I am able to move onto my next issue.

**Comment by mhobotpplnet** [comment] 2019-06-10 14:15
Thanks I'll give it a try.

**Comment by mhobotpplnet** [comment] 2019-06-10 14:35
Helm lint/package now works for me too. My dir structure was bit different but it works now. 

Thank you for help @kozchris 

This is what I had in my test gradle for that project
```
import org.unbrokendome.gradle.plugins.helm.command.tasks.*

plugins {
    id("org.unbroken-dome.helm")
}
plugins {
    id ('org.unbroken-dome.helm-commands')
}
helm {
    charts {
        create("myappname") {
            chartName.set("myappname")
            chartVersion.set("1.2.3")
            sourceDir.set(file("src/main/helm"))
        }
    }
}

helm { home = file("$buildDir/helm/home") }
```

**Comment by tkrullmann** [comment] 2019-06-18 15:09
Hi! Glad you figured out a solution.

I think the problem is that the `helmLint<Chart>` task did not have a dependency on `helmInitClient`, so if your helm home directory was missing, then it would fail because that directory is created by `helmInitClient`.

It should be fixed in the next release.

**Closed** 2019-06-18 15:13 UTC
